/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/predictor': typeof PredictorRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/tax': typeof TaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/predictor'
    | '/settings'
    | '/success'
    | '/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/predictor'
    | '/settings'
    | '/success'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/predictor'
    | '/settings'
    | '/success'
    | '/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PredictorRoute: typeof PredictorRoute
  SettingsRoute: typeof SettingsRoute
  SuccessRoute: typeof SuccessRoute
  TaxRoute: typeof TaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PredictorRoute: PredictorRoute,
  SettingsRoute: SettingsRoute,
  SuccessRoute: SuccessRoute,
  TaxRoute: TaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
